package com.cloudoptimizer.agent.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.time.Instant;
import java.util.List;

/**
 * Represents an AI agent's optimization decision for cloud resources.
 * 
 * Encapsulates the analysis results, recommendations, and confidence
 * metrics generated by the optimization agent for a specific resource
 * or set of resources.
 * 
 * @author Sibasis Padhi
 * @version 1.0
 * @since 2025
 */
@Getter
@Builder
@ToString
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AgentDecision {

    @JsonProperty("decision_id")
    private final String decisionId;

    @JsonProperty("timestamp")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "UTC")
    private final Instant timestamp;

    @JsonProperty("resource_id")
    private final String resourceId;

    @JsonProperty("resource_type")
    private final String resourceType;

    @JsonProperty("strategy")
    private final AgentStrategy strategy;

    @JsonProperty("recommendation")
    private final String recommendation;

    @JsonProperty("reasoning")
    private final String reasoning;

    @JsonProperty("confidence_score")
    private final Double confidenceScore;

    @JsonProperty("estimated_savings")
    private final Double estimatedSavings;

    @JsonProperty("estimated_savings_currency")
    private final String estimatedSavingsCurrency;

    @JsonProperty("impact_level")
    private final ImpactLevel impactLevel;

    @JsonProperty("action_items")
    private final List<String> actionItems;

    @JsonProperty("risks")
    private final List<String> risks;

    @JsonProperty("metrics_analyzed")
    private final List<String> metricsAnalyzed;

    @JsonProperty("recommended_heap_size_mb")
    private final Integer recommendedHeapSizeMb;

    @JsonProperty("concurrency_confidence")
    private final Double concurrencyConfidence;

    @JsonProperty("heap_confidence")
    private final Double heapConfidence;

    /**
     * Impact level classification for optimization decisions.
     */
    public enum ImpactLevel {
        LOW("Low Impact", "Minimal changes with low risk"),
        MEDIUM("Medium Impact", "Moderate changes with manageable risk"),
        HIGH("High Impact", "Significant changes requiring careful planning"),
        CRITICAL("Critical Impact", "Major changes with substantial risk and reward");

        private final String displayName;
        private final String description;

        ImpactLevel(String displayName, String description) {
            this.displayName = displayName;
            this.description = description;
        }

        public String getDisplayName() {
            return displayName;
        }

        public String getDescription() {
            return description;
        }
    }

}
